version: '3.7'

services:
    laravel-app:
      build: .
      ports:
        - "8088:80"
      volumes:
        - ./:/usr/share/nginx
      networks:
        - app-network

    mysql-app:
      image: mysql:8.0
      ports: 
        - "3306:3306"
      volumes:
        - .docker/dbdata:/var/lib/mysql
      environment:
        MYSQL_DATABASE: todolist
        MYSQL_ROOT_PASSWORD: root
      networks:
        - app-network
        
networks:
    app-network:
      driver: bridge
      